# 设置app标题-----

app_title <-'DMS数据中台V5.0';

# store data into rdbe in the rds database
app_id <- 'cpdms'

#设置数据库链接---

conn_be <- conn_rds('rdbe')



#设置链接---
conn <- conn_rds('cprds')

#加载表体UI


workAreaSetting <-tabItems(
  
 #系统A-Z-------
 load_ui(sytem_id = 'A',module_id = 'A01'),
 load_ui(sytem_id = 'A',module_id = 'A02'),
 load_ui(sytem_id = 'A',module_id = 'A03'),
 load_ui(sytem_id = 'A',module_id = 'A04'),
 load_ui(sytem_id = 'A',module_id = 'A05'),
 load_ui(sytem_id = 'A',module_id = 'A06'),
 load_ui(sytem_id = 'A',module_id = 'A07'),
 load_ui(sytem_id = 'A',module_id = 'A08'),
 load_ui(sytem_id = 'A',module_id = 'A09'),
 load_ui(sytem_id = 'A',module_id = 'A10'),
 load_ui(sytem_id = 'B',module_id = 'B01'),
 load_ui(sytem_id = 'B',module_id = 'B02'),
 load_ui(sytem_id = 'B',module_id = 'B03'),
 load_ui(sytem_id = 'B',module_id = 'B04'),
 load_ui(sytem_id = 'B',module_id = 'B05'),
 load_ui(sytem_id = 'B',module_id = 'B06'),
 load_ui(sytem_id = 'B',module_id = 'B07'),
 load_ui(sytem_id = 'B',module_id = 'B08'),
 load_ui(sytem_id = 'B',module_id = 'B09'),
 load_ui(sytem_id = 'B',module_id = 'B10'),
 load_ui(sytem_id = 'C',module_id = 'C01'),
 load_ui(sytem_id = 'C',module_id = 'C02'),
 load_ui(sytem_id = 'C',module_id = 'C03'),
 load_ui(sytem_id = 'C',module_id = 'C04'),
 load_ui(sytem_id = 'C',module_id = 'C05'),
 load_ui(sytem_id = 'C',module_id = 'C06'),
 load_ui(sytem_id = 'C',module_id = 'C07'),
 load_ui(sytem_id = 'C',module_id = 'C08'),
 load_ui(sytem_id = 'C',module_id = 'C09'),
 load_ui(sytem_id = 'C',module_id = 'C10'),
 load_ui(sytem_id = 'D',module_id = 'D01'),
 load_ui(sytem_id = 'D',module_id = 'D02'),
 load_ui(sytem_id = 'D',module_id = 'D03'),
 load_ui(sytem_id = 'D',module_id = 'D04'),
 load_ui(sytem_id = 'D',module_id = 'D05'),
 load_ui(sytem_id = 'D',module_id = 'D06'),
 load_ui(sytem_id = 'D',module_id = 'D07'),
 load_ui(sytem_id = 'D',module_id = 'D08'),
 load_ui(sytem_id = 'D',module_id = 'D09'),
 load_ui(sytem_id = 'D',module_id = 'D10'),
 load_ui(sytem_id = 'E',module_id = 'E01'),
 load_ui(sytem_id = 'E',module_id = 'E02'),
 load_ui(sytem_id = 'E',module_id = 'E03'),
 load_ui(sytem_id = 'E',module_id = 'E04'),
 load_ui(sytem_id = 'E',module_id = 'E05'),
 load_ui(sytem_id = 'E',module_id = 'E06'),
 load_ui(sytem_id = 'E',module_id = 'E07'),
 load_ui(sytem_id = 'E',module_id = 'E08'),
 load_ui(sytem_id = 'E',module_id = 'E09'),
 load_ui(sytem_id = 'E',module_id = 'E10'),
 load_ui(sytem_id = 'F',module_id = 'F01'),
 load_ui(sytem_id = 'F',module_id = 'F02'),
 load_ui(sytem_id = 'F',module_id = 'F03'),
 load_ui(sytem_id = 'F',module_id = 'F04'),
 load_ui(sytem_id = 'F',module_id = 'F05'),
 load_ui(sytem_id = 'F',module_id = 'F06'),
 load_ui(sytem_id = 'F',module_id = 'F07'),
 load_ui(sytem_id = 'F',module_id = 'F08'),
 load_ui(sytem_id = 'F',module_id = 'F09'),
 load_ui(sytem_id = 'F',module_id = 'F10'),
 load_ui(sytem_id = 'G',module_id = 'G01'),
 load_ui(sytem_id = 'G',module_id = 'G02'),
 load_ui(sytem_id = 'G',module_id = 'G03'),
 load_ui(sytem_id = 'G',module_id = 'G04'),
 load_ui(sytem_id = 'G',module_id = 'G05'),
 load_ui(sytem_id = 'G',module_id = 'G06'),
 load_ui(sytem_id = 'G',module_id = 'G07'),
 load_ui(sytem_id = 'G',module_id = 'G08'),
 load_ui(sytem_id = 'G',module_id = 'G09'),
 load_ui(sytem_id = 'G',module_id = 'G10'),
 load_ui(sytem_id = 'H',module_id = 'H01'),
 load_ui(sytem_id = 'H',module_id = 'H02'),
 load_ui(sytem_id = 'H',module_id = 'H03'),
 load_ui(sytem_id = 'H',module_id = 'H04'),
 load_ui(sytem_id = 'H',module_id = 'H05'),
 load_ui(sytem_id = 'H',module_id = 'H06'),
 load_ui(sytem_id = 'H',module_id = 'H07'),
 load_ui(sytem_id = 'H',module_id = 'H08'),
 load_ui(sytem_id = 'H',module_id = 'H09'),
 load_ui(sytem_id = 'H',module_id = 'H10'),
 load_ui(sytem_id = 'I',module_id = 'I01'),
 load_ui(sytem_id = 'I',module_id = 'I02'),
 load_ui(sytem_id = 'I',module_id = 'I03'),
 load_ui(sytem_id = 'I',module_id = 'I04'),
 load_ui(sytem_id = 'I',module_id = 'I05'),
 load_ui(sytem_id = 'I',module_id = 'I06'),
 load_ui(sytem_id = 'I',module_id = 'I07'),
 load_ui(sytem_id = 'I',module_id = 'I08'),
 load_ui(sytem_id = 'I',module_id = 'I09'),
 load_ui(sytem_id = 'I',module_id = 'I10'),
 load_ui(sytem_id = 'J',module_id = 'J01'),
 load_ui(sytem_id = 'J',module_id = 'J02'),
 load_ui(sytem_id = 'J',module_id = 'J03'),
 load_ui(sytem_id = 'J',module_id = 'J04'),
 load_ui(sytem_id = 'J',module_id = 'J05'),
 load_ui(sytem_id = 'J',module_id = 'J06'),
 load_ui(sytem_id = 'J',module_id = 'J07'),
 load_ui(sytem_id = 'J',module_id = 'J08'),
 load_ui(sytem_id = 'J',module_id = 'J09'),
 load_ui(sytem_id = 'J',module_id = 'J10'),
 load_ui(sytem_id = 'K',module_id = 'K01'),
 load_ui(sytem_id = 'K',module_id = 'K02'),
 load_ui(sytem_id = 'K',module_id = 'K03'),
 load_ui(sytem_id = 'K',module_id = 'K04'),
 load_ui(sytem_id = 'K',module_id = 'K05'),
 load_ui(sytem_id = 'K',module_id = 'K06'),
 load_ui(sytem_id = 'K',module_id = 'K07'),
 load_ui(sytem_id = 'K',module_id = 'K08'),
 load_ui(sytem_id = 'K',module_id = 'K09'),
 load_ui(sytem_id = 'K',module_id = 'K10'),
 load_ui(sytem_id = 'L',module_id = 'L01'),
 load_ui(sytem_id = 'L',module_id = 'L02'),
 load_ui(sytem_id = 'L',module_id = 'L03'),
 load_ui(sytem_id = 'L',module_id = 'L04'),
 load_ui(sytem_id = 'L',module_id = 'L05'),
 load_ui(sytem_id = 'L',module_id = 'L06'),
 load_ui(sytem_id = 'L',module_id = 'L07'),
 load_ui(sytem_id = 'L',module_id = 'L08'),
 load_ui(sytem_id = 'L',module_id = 'L09'),
 load_ui(sytem_id = 'L',module_id = 'L10'),
 load_ui(sytem_id = 'M',module_id = 'M01'),
 load_ui(sytem_id = 'M',module_id = 'M02'),
 load_ui(sytem_id = 'M',module_id = 'M03'),
 load_ui(sytem_id = 'M',module_id = 'M04'),
 load_ui(sytem_id = 'M',module_id = 'M05'),
 load_ui(sytem_id = 'M',module_id = 'M06'),
 load_ui(sytem_id = 'M',module_id = 'M07'),
 load_ui(sytem_id = 'M',module_id = 'M08'),
 load_ui(sytem_id = 'M',module_id = 'M09'),
 load_ui(sytem_id = 'M',module_id = 'M10'),
 load_ui(sytem_id = 'N',module_id = 'N01'),
 load_ui(sytem_id = 'N',module_id = 'N02'),
 load_ui(sytem_id = 'N',module_id = 'N03'),
 load_ui(sytem_id = 'N',module_id = 'N04'),
 load_ui(sytem_id = 'N',module_id = 'N05'),
 load_ui(sytem_id = 'N',module_id = 'N06'),
 load_ui(sytem_id = 'N',module_id = 'N07'),
 load_ui(sytem_id = 'N',module_id = 'N08'),
 load_ui(sytem_id = 'N',module_id = 'N09'),
 load_ui(sytem_id = 'N',module_id = 'N10'),
 load_ui(sytem_id = 'O',module_id = 'O01'),
 load_ui(sytem_id = 'O',module_id = 'O02'),
 load_ui(sytem_id = 'O',module_id = 'O03'),
 load_ui(sytem_id = 'O',module_id = 'O04'),
 load_ui(sytem_id = 'O',module_id = 'O05'),
 load_ui(sytem_id = 'O',module_id = 'O06'),
 load_ui(sytem_id = 'O',module_id = 'O07'),
 load_ui(sytem_id = 'O',module_id = 'O08'),
 load_ui(sytem_id = 'O',module_id = 'O09'),
 load_ui(sytem_id = 'O',module_id = 'O10'),
 load_ui(sytem_id = 'P',module_id = 'P01'),
 load_ui(sytem_id = 'P',module_id = 'P02'),
 load_ui(sytem_id = 'P',module_id = 'P03'),
 load_ui(sytem_id = 'P',module_id = 'P04'),
 load_ui(sytem_id = 'P',module_id = 'P05'),
 load_ui(sytem_id = 'P',module_id = 'P06'),
 load_ui(sytem_id = 'P',module_id = 'P07'),
 load_ui(sytem_id = 'P',module_id = 'P08'),
 load_ui(sytem_id = 'P',module_id = 'P09'),
 load_ui(sytem_id = 'P',module_id = 'P10'),
 load_ui(sytem_id = 'Q',module_id = 'Q01'),
 load_ui(sytem_id = 'Q',module_id = 'Q02'),
 load_ui(sytem_id = 'Q',module_id = 'Q03'),
 load_ui(sytem_id = 'Q',module_id = 'Q04'),
 load_ui(sytem_id = 'Q',module_id = 'Q05'),
 load_ui(sytem_id = 'Q',module_id = 'Q06'),
 load_ui(sytem_id = 'Q',module_id = 'Q07'),
 load_ui(sytem_id = 'Q',module_id = 'Q08'),
 load_ui(sytem_id = 'Q',module_id = 'Q09'),
 load_ui(sytem_id = 'Q',module_id = 'Q10'),
 load_ui(sytem_id = 'R',module_id = 'R01'),
 load_ui(sytem_id = 'R',module_id = 'R02'),
 load_ui(sytem_id = 'R',module_id = 'R03'),
 load_ui(sytem_id = 'R',module_id = 'R04'),
 load_ui(sytem_id = 'R',module_id = 'R05'),
 load_ui(sytem_id = 'R',module_id = 'R06'),
 load_ui(sytem_id = 'R',module_id = 'R07'),
 load_ui(sytem_id = 'R',module_id = 'R08'),
 load_ui(sytem_id = 'R',module_id = 'R09'),
 load_ui(sytem_id = 'R',module_id = 'R10'),
 load_ui(sytem_id = 'S',module_id = 'S01'),
 load_ui(sytem_id = 'S',module_id = 'S02'),
 load_ui(sytem_id = 'S',module_id = 'S03'),
 load_ui(sytem_id = 'S',module_id = 'S04'),
 load_ui(sytem_id = 'S',module_id = 'S05'),
 load_ui(sytem_id = 'S',module_id = 'S06'),
 load_ui(sytem_id = 'S',module_id = 'S07'),
 load_ui(sytem_id = 'S',module_id = 'S08'),
 load_ui(sytem_id = 'S',module_id = 'S09'),
 load_ui(sytem_id = 'S',module_id = 'S10'),
 load_ui(sytem_id = 'T',module_id = 'T01'),
 load_ui(sytem_id = 'T',module_id = 'T02'),
 load_ui(sytem_id = 'T',module_id = 'T03'),
 load_ui(sytem_id = 'T',module_id = 'T04'),
 load_ui(sytem_id = 'T',module_id = 'T05'),
 load_ui(sytem_id = 'T',module_id = 'T06'),
 load_ui(sytem_id = 'T',module_id = 'T07'),
 load_ui(sytem_id = 'T',module_id = 'T08'),
 load_ui(sytem_id = 'T',module_id = 'T09'),
 load_ui(sytem_id = 'T',module_id = 'T10'),
 load_ui(sytem_id = 'U',module_id = 'U01'),
 load_ui(sytem_id = 'U',module_id = 'U02'),
 load_ui(sytem_id = 'U',module_id = 'U03'),
 load_ui(sytem_id = 'U',module_id = 'U04'),
 load_ui(sytem_id = 'U',module_id = 'U05'),
 load_ui(sytem_id = 'U',module_id = 'U06'),
 load_ui(sytem_id = 'U',module_id = 'U07'),
 load_ui(sytem_id = 'U',module_id = 'U08'),
 load_ui(sytem_id = 'U',module_id = 'U09'),
 load_ui(sytem_id = 'U',module_id = 'U10'),
 load_ui(sytem_id = 'V',module_id = 'V01'),
 load_ui(sytem_id = 'V',module_id = 'V02'),
 load_ui(sytem_id = 'V',module_id = 'V03'),
 load_ui(sytem_id = 'V',module_id = 'V04'),
 load_ui(sytem_id = 'V',module_id = 'V05'),
 load_ui(sytem_id = 'V',module_id = 'V06'),
 load_ui(sytem_id = 'V',module_id = 'V07'),
 load_ui(sytem_id = 'V',module_id = 'V08'),
 load_ui(sytem_id = 'V',module_id = 'V09'),
 load_ui(sytem_id = 'V',module_id = 'V10'),
 load_ui(sytem_id = 'W',module_id = 'W01'),
 load_ui(sytem_id = 'W',module_id = 'W02'),
 load_ui(sytem_id = 'W',module_id = 'W03'),
 load_ui(sytem_id = 'W',module_id = 'W04'),
 load_ui(sytem_id = 'W',module_id = 'W05'),
 load_ui(sytem_id = 'W',module_id = 'W06'),
 load_ui(sytem_id = 'W',module_id = 'W07'),
 load_ui(sytem_id = 'W',module_id = 'W08'),
 load_ui(sytem_id = 'W',module_id = 'W09'),
 load_ui(sytem_id = 'W',module_id = 'W10'),
 load_ui(sytem_id = 'X',module_id = 'X01'),
 load_ui(sytem_id = 'X',module_id = 'X02'),
 load_ui(sytem_id = 'X',module_id = 'X03'),
 load_ui(sytem_id = 'X',module_id = 'X04'),
 load_ui(sytem_id = 'X',module_id = 'X05'),
 load_ui(sytem_id = 'X',module_id = 'X06'),
 load_ui(sytem_id = 'X',module_id = 'X07'),
 load_ui(sytem_id = 'X',module_id = 'X08'),
 load_ui(sytem_id = 'X',module_id = 'X09'),
 load_ui(sytem_id = 'X',module_id = 'X10'),
 load_ui(sytem_id = 'Y',module_id = 'Y01'),
 load_ui(sytem_id = 'Y',module_id = 'Y02'),
 load_ui(sytem_id = 'Y',module_id = 'Y03'),
 load_ui(sytem_id = 'Y',module_id = 'Y04'),
 load_ui(sytem_id = 'Y',module_id = 'Y05'),
 load_ui(sytem_id = 'Y',module_id = 'Y06'),
 load_ui(sytem_id = 'Y',module_id = 'Y07'),
 load_ui(sytem_id = 'Y',module_id = 'Y08'),
 load_ui(sytem_id = 'Y',module_id = 'Y09'),
 load_ui(sytem_id = 'Y',module_id = 'Y10'),
 load_ui(sytem_id = 'Z',module_id = 'Z01'),
 load_ui(sytem_id = 'Z',module_id = 'Z02'),
 load_ui(sytem_id = 'Z',module_id = 'Z03'),
 load_ui(sytem_id = 'Z',module_id = 'Z04'),
 load_ui(sytem_id = 'Z',module_id = 'Z05'),
 load_ui(sytem_id = 'Z',module_id = 'Z06'),
 load_ui(sytem_id = 'Z',module_id = 'Z07'),
 load_ui(sytem_id = 'Z',module_id = 'Z08'),
 load_ui(sytem_id = 'Z',module_id = 'Z09'),
 load_ui(sytem_id = 'Z',module_id = 'Z10')



  
  
)






